# Generated by Django 2.2.7 on 2019-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_on_delete_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proformatask_hash',
            field=models.UUIDField(editable=False, help_text='Hash for proforma task file', null=True),
        ),
    ]
